apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: residential-caribou-go 
  janus-idp.io/tekton: residential-caribou-go
  backstage.io/kubernetes-id: residential-caribou-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: residential-caribou-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  