apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: residential-caribou-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: residential-caribou-go 
  name: residential-caribou-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: residential-caribou-go 
